---
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  LoopMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn: !GetAtt StatesExecutionRole.Arn
      DefinitionString: |-
          {
            "StartAt": "Init",
            "States": {
              "Init": {
                "Type": "Pass",
                "Result": ["1", "2", "3", "DONE"],
                "ResultPath": "$.Items",
                "Next": "Loop Condition"
              },
              "Loop Condition": {
                "Type": "Choice",
                "Choices": [
                  {
                    "Not": {
                      "Variable": "$.Items[0]",
                      "StringEquals": "DONE"
                    },
                    "Next": "RunJob"
                  }
                ],
                "Default": "Finish"
              },
              "Finish": {
                "Type": "Succeed"
              },
              "RunJob": {
                "Type": "Wait",
                "Seconds": 10,
                "Next": "Pop Loop Element"
              },
              "Pop Loop Element": {
                "Type": "Pass",
                "Parameters": {
                  "Items.$": "$.Items[1:]"
                },
                "Next": "Loop Condition"
              }
            }
          }

  StatesExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: "sts:AssumeRole"
